export type NewsItem = {
  title: string;
  url: string;
  source: string;
  date?: string;
};

// Auto-generated by scripts/update-ai-news.mjs (do not hand-edit)
export const aiNews: NewsItem[] = [
  { title: `How we used Gemini to build Google I/O 2026`, url: `https://blog.google/innovation-and-ai/technology/ai/io-2026-google-ai/`, source: `Google AI`, date: `2026-06-01` },
  { title: `Building the infrastructure for the Intelligence Age in Michigan`, url: `https://openai.com/index/stargate-michigan-data-center`, source: `OpenAI`, date: `2026-06-01` },
  { title: `PhyDrawGen: Physically Grounded Diagram Generation from Natural Language`, url: `https://arxiv.org/abs/2605.30512`, source: `arXiv cs.AI`, date: `2026-06-01` },
  { title: `Take our I/O 2026 quiz, vibe coded in Google AI Studio.`, url: `https://blog.google/innovation-and-ai/technology/ai/io-2026-vibe-coded-quiz/`, source: `Google AI`, date: `2026-05-29` },
  { title: `Boston Children’s uses AI to unlock new diagnoses`, url: `https://openai.com/index/boston-childrens-hospital`, source: `OpenAI`, date: `2026-05-29` },
  { title: `Physically Viable World Models: A Case for Query-Conditioned Embodied AI`, url: `https://arxiv.org/abs/2605.30542`, source: `arXiv cs.AI`, date: `2026-06-01` },
  { title: `9 demos of Gemini Omni and Gemini 3.5 in action`, url: `https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-omni-3-5-videos/`, source: `Google AI`, date: `2026-05-29` },
  { title: `How Braintrust turns customer requests into code with Codex`, url: `https://openai.com/index/braintrust`, source: `OpenAI`, date: `2026-05-29` },
  { title: `Transforming and Encoding FTS for SAT Solving: What Helps, What Hurts (Extended Version)`, url: `https://arxiv.org/abs/2605.30563`, source: `arXiv cs.AI`, date: `2026-06-01` },
  { title: `Check out real-life AI prototypes from the Futures Lab.`, url: `https://blog.google/innovation-and-ai/technology/ai/university-waterloo-labs/`, source: `Google AI`, date: `2026-05-29` },
  { title: `Strengthening societal resilience with Rosalind Biodefense`, url: `https://openai.com/index/strengthening-societal-resilience-with-rosalind-biodefense`, source: `OpenAI`, date: `2026-05-29` },
  { title: `Procedural Generation of First Person Shooter Maps using Map-Elites`, url: `https://arxiv.org/abs/2605.30570`, source: `arXiv cs.AI`, date: `2026-06-01` },
];
