export type NewsItem = {
  title: string;
  url: string;
  source: string;
  date?: string;
};

// Auto-generated by scripts/update-ai-news.mjs (do not hand-edit)
export const aiNews: NewsItem[] = [
  { title: `New experts join Google’s AI & Economy team`, url: `https://blog.google/innovation-and-ai/technology/ai/expanding-ai-economy-research-bench/`, source: `Google AI`, date: `2026-09-18` },
  { title: `Advisory Group on Mathematics and Artificial Intelligence`, url: `https://openai.com/index/advisory-group-on-mathematics-and-ai`, source: `OpenAI`, date: `2026-09-21` },
  { title: `RBS-Attention: Radius-Bounded Sparse Prefill for Long-Context Large Language Models`, url: `https://arxiv.org/abs/2609.20971`, source: `arXiv cs.AI`, date: `2026-09-21` },
  { title: `Co-creating the future of fashion with Google`, url: `https://blog.google/innovation-and-ai/technology/ai/google-flow-fashion-week/`, source: `Google AI`, date: `2026-09-18` },
  { title: `Building standards for the next phase of AI`, url: `https://openai.com/index/building-standards-next-phase-ai`, source: `OpenAI`, date: `2026-09-21` },
  { title: `Attention-Aware Routing: Coupling Routing and Attention in MoEs`, url: `https://arxiv.org/abs/2609.20974`, source: `arXiv cs.AI`, date: `2026-09-21` },
  { title: `Making global data easier to explore`, url: `https://blog.google/innovation-and-ai/technology/ai/google-un-data-commons-platform/`, source: `Google AI`, date: `2026-09-17` },
  { title: `Expanding OpenAI Academy with new learning paths`, url: `https://openai.com/index/expanding-openai-academy-with-new-learning-paths`, source: `OpenAI`, date: `2026-09-21` },
  { title: `CaLR: Causal Latent Revision for Robust Diffusion Reasoning`, url: `https://arxiv.org/abs/2609.20981`, source: `arXiv cs.AI`, date: `2026-09-21` },
  { title: `AI for Societal Impact`, url: `https://blog.google/innovation-and-ai/technology/ai/ai-for-societal-impact/`, source: `Google AI`, date: `2026-09-15` },
  { title: `How V7 gives AI agents institutional memory`, url: `https://openai.com/index/v7`, source: `OpenAI`, date: `2026-09-21` },
  { title: `LoRA Enhanced Contrastive Learning with SAS Vision Transformers`, url: `https://arxiv.org/abs/2609.21061`, source: `arXiv cs.AI`, date: `2026-09-21` },
];
