export type NewsItem = {
  title: string;
  url: string;
  source: string;
  date?: string;
};

// Auto-generated by scripts/update-ai-news.mjs (do not hand-edit)
export const aiNews: NewsItem[] = [
  { title: `New research shows how AMIE, our medical AI, could help manage health conditions.`, url: `https://blog.google/innovation-and-ai/models-and-research/google-research/amie-for-disease-management-in-nature/`, source: `Google AI`, date: `2026-06-17` },
  { title: `Patch the Planet: a Daybreak initiative to support open source maintainers`, url: `https://openai.com/index/patch-the-planet`, source: `OpenAI`, date: `2026-06-22` },
  { title: `We’re strengthening our presence in Alabama through new investments and community support.`, url: `https://blog.google/innovation-and-ai/infrastructure-and-cloud/global-network/alabama-investment-june-2026/`, source: `Google AI`, date: `2026-06-15` },
  { title: `Daybreak: Tools for securing every organization in the world`, url: `https://openai.com/index/daybreak-securing-the-world`, source: `OpenAI`, date: `2026-06-22` },
  { title: `Our new community investments in Virginia support local jobs and expand energy affordability.`, url: `https://blog.google/innovation-and-ai/infrastructure-and-cloud/global-network/virginia-community-investments/`, source: `Google AI`, date: `2026-06-11` },
  { title: `Samsung Electronics brings ChatGPT and Codex to employees`, url: `https://openai.com/index/samsung-electronics-chatgpt-codex-deployment`, source: `OpenAI`, date: `2026-06-21` },
  { title: `The latest AI news we announced in May 2026`, url: `https://blog.google/innovation-and-ai/technology/ai/google-ai-updates-may-2026/`, source: `Google AI`, date: `2026-06-05` },
  { title: `New usage analytics and updated spend controls for enterprises`, url: `https://openai.com/index/chatgpt-enterprise-spend-controls`, source: `OpenAI`, date: `2026-06-18` },
  { title: `Improving health intelligence in ChatGPT`, url: `https://openai.com/index/improving-health-intelligence-in-chatgpt`, source: `OpenAI`, date: `2026-06-18` },
  { title: `Using AI to help physicians diagnose rare genetic diseases affecting children`, url: `https://openai.com/index/diagnose-rare-childhood-diseases`, source: `OpenAI`, date: `2026-06-18` },
  { title: `A near-autonomous AI chemist improves a challenging reaction in medicinal chemistry`, url: `https://openai.com/index/ai-chemist-improves-reaction`, source: `OpenAI`, date: `2026-06-17` },
  { title: `Introducing LifeSciBench`, url: `https://openai.com/index/introducing-life-sci-bench`, source: `OpenAI`, date: `2026-06-17` },
];
